name: Build and Push Multi-arch Docker Image

# 定义触发条件，比如代码推送到main分支时触发
on:
  workflow_dispatch:
    description: "手动触发构建和推送多架构 Docker 镜像到 Docker Hub" # 可选改进 4

# 定义工作流中的作业
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # 设置环境变量
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/docker-coremark
      VERSION: $(date +%Y%m%d)

    # 定义作业中的步骤
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置Docker构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 登录DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 构建Docker镜像（支持多平台）并输出日志到指定文件
      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386,linux/ppc64le,linux/s390x \
            --file Dockerfile \
            -t $IMAGE_NAME \
            -t $IMAGE_NAME:$VERSION \
            ./ --push  # 将 . 改为 ./

