name: Build and Push Multi-arch Docker Image

# 定义触发条件，比如代码推送到main分支时触发
on:
  workflow_dispatch:

# 定义工作流中的作业
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # 设置环境变量
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/docker-coremark
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      VERSION: $(date +%Y%m%d)

    # 定义作业中的步骤
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置Docker构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 登录DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 构建Docker镜像（支持多平台）并输出日志到指定文件
      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386,linux/ppc64le,linux/s390x --file Dockerfile -t $IMAGE_NAME . 2>&1 | tee build.log

      # 给镜像打上年月日 tag
      - name: Tag Docker image with date
        run: docker tag $IMAGE_NAME:latest $IMAGE_NAME:$(date +%Y%m%d)

      # 推送Docker镜像到DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$(date +%Y%m%d)
